add working write_fv3_spread for fv3-lam
NOAA-EMC/GSI pull request #196
Opened 2021-08-10 18:04 UTC by TingLei-NOAA

it is associated with https://github.com/NOAA-EMC/GSI/issues/189.
Now, the GSI can dump ensemble spread on the ensemble analysis grid for FV3-LAM ensembles.

2021-08-11 11:33 UTC, TingLei-NOAA commented
Mike,
Thanks.
I 'd like wanshu and Cory Martin to be the reviewers.
BTW:  we can't choose reviewers online now , right?   Just want to make
sure I didn't miss that function causing you have to ask me (manually) :).
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624


On Wed, Aug 11, 2021 at 6:14 AM MichaelLueken-NOAA ***@***.***>
wrote:

> @TingLei-NOAA <https://github.com/TingLei-NOAA> Who would you like to
> have review your changes? I'll assign them as a reviewer and begin the
> process of getting these changes into the authoritative repo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GSI/pull/196#issuecomment-896696762>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEFS7ASYVGPS3NWI74UFKLT4JEO3ANCNFSM5B4TS7LA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-11 11:41 UTC, MichaelLueken-NOAA commented
@TingLei-NOAA Unfortunately, I'm the only person who can assign reviewers to PRs.  I'll assign Wan-Shu and Cory now.

2021-08-11 11:54 UTC, TingLei-NOAA commented
Mike,
Thanks a lot for your confirmation on this.  Really appreciate your help
through all of this!
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624


On Wed, Aug 11, 2021 at 7:41 AM MichaelLueken-NOAA ***@***.***>
wrote:

> @TingLei-NOAA <https://github.com/TingLei-NOAA> Unfortunately, I'm the
> only person who can assign reviewers to PRs. I'll assign Wan-Shu and Cory
> now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GSI/pull/196#issuecomment-896755100>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEFS7D2XMQVED6DOSY4AETT4JOXDANCNFSM5B4TS7LA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-11 12:53 UTC, CoryMartin-NOAA requested changes
I think code looks fine from what I can tell, but some changes needed for documentation clean up

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/cplr_get_fv3_regional_ensperts.f90
> +    use  write_fv3_enspread_mod, only: write_fv3_enspread
extra space here after `use`, not sure if it needs fixed or not though?

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/cplr_get_fv3_regional_ensperts.f90
> -    if(regional_ensemble_option == 1)then
since `if` block is removed, should change the indentation of this section.

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/write_fv3_spread.f90
> +! module:   write_incr
Change this documentation block to reflect the new file name.

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/write_fv3_spread.f90
> +!clt    if(mype_out.lt.0) then
Remove these commented out lines if not needed

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/write_fv3_spread.f90
> +    ! get levels that are nearest the tropopause pressure
Remove this comment as it refers to code that is removed and not needed here.

2021-08-11 12:53 UTC, CoryMartin-NOAA commented on src/gsi/write_fv3_spread.f90
> +       write(6,*) "FV3 netCDF increment written, file= "//trim(filename)//".nc"
not writing an increment here

2021-08-11 13:52 UTC, CoryMartin-NOAA approved these changes
Thanks Ting, I think everything looks good to me but I didn't test compiling/running

2021-08-11 13:54 UTC, WanshuWu-NOAA approved these changes
Ting, 
1) Please add change info to program history log in cplr_get_fv3_regional_ensperts.f90.
2)Thanks for the bug fix in mod_fv3_lola.f90. Please add info to the program history.
3)If Cory's write_fv3_enspread_mod already included in other directory, should we just link to it? (To save space and decrease maintenance efforts)

2021-08-11 14:19 UTC, TingLei-NOAA commented
@WanshuWu-NOAA  Thanks.  I had changed them for your comments 1-2. 
About the point 3, the write_fv3_snespread_mod was created with this PR on the basis of write_inc . I keep the history of write_inc to , hopefully , better document the history of the program . I did a little change in the doc block and hope it is clearer now. Please let me know if more clarification is needed on this.

2021-08-11 15:01 UTC, WanshuWu-NOAA commented
@TingLei-NOAA Thanks.

2021-08-13 14:22 UTC, MichaelLueken-NOAA requested changes
@TingLei-NOAA I have completed my review of your changes.  The changes were visually inspected and look fine.  I cloned your changes to WCOSS and compiled the code without issue.  The regression tests were run and all passed successfully.  I then recompiled in debug mode.  Several unused variables were flagged.  The debug tests were run and all passed.  Please follow these steps to correct the commit messages and remove the unused variables.

Checkout temporary fork to correct commit message and remove unused variables:
1) git clone --recursive git@github.com:TingLei-daprediction/GSI.git update
2) cd update
3) git checkout feature/GSI_FV3LAM_write_ensprd
4) git submodule update
5) git reset --soft HEAD~1
6) git reset --soft HEAD~1
7) git reset --soft HEAD~1
8) git reset --soft HEAD~1
`9) git commit -m "GitHub Issue NOAA-EMC/GSI#189. Add working write_fv3_spread for fv3-lam."`
10) Please remove unused variables from the two subroutines
11) git add cplr_get_fv3_regional_ensperts.f90 write_fv3_spread.f90
12) git commit --amend
13) Save and quit without changing commit message
14) git push origin feature/GSI_FV3LAM_write_ensprd --force

If you have any questions or encounter issues, please let me know.

2021-08-13 20:00 UTC, TingLei-NOAA commented
Mike,
Thanks a lot for your detailed instructions.  I have finished those steps
except for step 1 and 4 for permission issue, which I think will not affect
the required codes modifications and the git processing.  The
compiling shows there are no unused vars in those two subs.
Please let me know if any problems.
Have a good weekend.
Ting

On Fri, Aug 13, 2021 at 10:22 AM MichaelLueken-NOAA <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @TingLei-NOAA <https://github.com/TingLei-NOAA> I have completed my
> review of your changes. The changes were visually inspected and look fine.
> I cloned your changes to WCOSS and compiled the code without issue. The
> regression tests were run and all passed successfully. I then recompiled in
> debug mode. Several unused variables were flagged. The debug tests were run
> and all passed. Please follow these steps to correct the commit messages
> and remove the unused variables.
>
> Checkout temporary fork to correct commit message and remove unused
> variables:
>
>    1. git clone --recursive ***@***.***:TingLei-daprediction/GSI.git
>    update
>    2. cd update
>    3. git checkout feature/GSI_FV3LAM_write_ensprd
>    4. git submodule update
>    5. git reset --soft HEAD~1
>    6. git reset --soft HEAD~1
>    7. git reset --soft HEAD~1
>    8. git reset --soft HEAD~1
>    9. git commit -m "GitHub Issue #189
>    <https://github.com/NOAA-EMC/GSI/issues/189>. Add working
>    write_fv3_spread for fv3-lam."
>    10. Please remove unused variables from the two subroutines
>    11. git add cplr_get_fv3_regional_ensperts.f90 write_fv3_spread.f90
>    12. git commit --amend
>    13. Save and quit without changing commit message
>    14. git push origin feature/GSI_FV3LAM_write_ensprd --force
>
> If you have any questions or encounter issues, please let me know.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688455565>:
>
> > @@ -460,7 +465,7 @@ subroutine general_read_fv3_regional(this,fv3_filenameginput,g_ps,g_u,g_v,g_tv,g
>
>    return
>    end subroutine general_read_fv3_regional
> -  subroutine ens_spread_dualres_regional_fv3_regional(this,mype,en_perts,nelen,en_bar)
> +  subroutine ens_spread_dualres_regional_fv3_regional(this,mype,en_perts,nelen)
>
> While compiling in debug mode, mype was identified as being unused. Please
> remove unused variable.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688456162>:
>
> > @@ -487,8 +491,7 @@ subroutine ens_spread_dualres_regional_fv3_regional(this,mype,en_perts,nelen,en_
>    !$$$ end documentation block
>    !
>      use kinds, only: r_single,r_kind,i_kind
> -    use hybrid_ensemble_parameters, only: n_ens,grd_ens,grd_anl,p_e2a,uv_hyb_ens, &
> -                                          regional_ensemble_option
> +    use hybrid_ensemble_parameters, only: n_ens,grd_ens,grd_anl
>      use general_sub2grid_mod, only: sub2grid_info,general_sub2grid_create_info,general_sube2suba
>      use constants, only:  zero,two,half,one
>      use control_vectors, only: cvars2d,cvars3d,nc2d,nc3d
>
> While compiling in debug mode, both nc2d and nc3d were identified as
> unused. Please remove unused variables.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688457236>:
>
> >      logical regional
>      integer(i_kind) num_fields,inner_vars,istat,istatus
> -    logical,allocatable::vector(:)
>      real(r_kind),pointer,dimension(:,:,:):: st,vp,tv,rh,oz,cw
>
> While compiling in debug mode, st, vp, tv, rh, oz, and cw were identified
> as unused. Please remove unused variables.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688457632>:
>
> >      logical regional
>      integer(i_kind) num_fields,inner_vars,istat,istatus
> -    logical,allocatable::vector(:)
>      real(r_kind),pointer,dimension(:,:,:):: st,vp,tv,rh,oz,cw
>      real(r_kind),pointer,dimension(:,:):: ps
>
> While compiling in debug mode, ps was identified as unused. Please remove
> unused variable.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688459413>:
>
> >      integer(i_kind),intent(in):: mype
>      type(gsi_bundle),allocatable, intent(in   ) :: en_perts(:,:)
>      integer(i_kind), intent(in   ):: nelen
>
>      type(gsi_bundle):: sube,suba
>      type(gsi_grid):: grid_ens,grid_anl
> -    real(r_kind) sp_norm,sig_norm_sq_inv
> -    type(sub2grid_info)::se,sa
> +    real(r_kind) sp_norm
>      integer(i_kind) k
>
> While compiling in debug mode, k was identified as unused. Please remove
> unused variable.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688460138>:
>
> >
> -    integer(i_kind) i,n,ic3
> +    integer(i_kind) i,j,n,ic3,mm1
>
> While compiling in debug mode, j, ic3, and mm1 were identified as unused.
> Please remove unused variables.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688460483>:
>
> >
> -    integer(i_kind) i,n,ic3
> +    integer(i_kind) i,j,n,ic3,mm1
>      logical regional
>
> While compiling in debug mode, regional was identified as unused. Please
> remove unused variable.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688461077>:
>
> >
> -    integer(i_kind) i,n,ic3
> +    integer(i_kind) i,j,n,ic3,mm1
>      logical regional
>      integer(i_kind) num_fields,inner_vars,istat,istatus
>
> While compiling in debug mode, num_fields, inner_vars, and istat were
> identified as unused. Please remove unused variables.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688461423>:
>
> >      logical regional
>      integer(i_kind) num_fields,inner_vars,istat,istatus
> -    logical,allocatable::vector(:)
>      real(r_kind),pointer,dimension(:,:,:):: st,vp,tv,rh,oz,cw
>      real(r_kind),pointer,dimension(:,:):: ps
>      real(r_kind),dimension(grd_anl%lat2,grd_anl%lon2,grd_anl%nsig),target::dum3
>
> While compiling in debug mode, dum3 was identified as unused. Please
> remove unused variable.
> ------------------------------
>
> In src/gsi/cplr_get_fv3_regional_ensperts.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688461724>:
>
> >      logical regional
>      integer(i_kind) num_fields,inner_vars,istat,istatus
> -    logical,allocatable::vector(:)
>      real(r_kind),pointer,dimension(:,:,:):: st,vp,tv,rh,oz,cw
>      real(r_kind),pointer,dimension(:,:):: ps
>      real(r_kind),dimension(grd_anl%lat2,grd_anl%lon2,grd_anl%nsig),target::dum3
>      real(r_kind),dimension(grd_anl%lat2,grd_anl%lon2),target::dum2
>
> While compiling in debug mode, dum2 was identified as unused. Please
> remove unused variable.
> ------------------------------
>
> In src/gsi/write_fv3_spread.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r688462288>:
>
> > +! Subroutines Included:
> +!   sub write_fv3_enspread - writes netCDF spread for FV3-LAM
> +!
> +!$$$ end documentation block
> +
> +  implicit none
> +  private
> +  public write_fv3_enspread
> +
> +  interface write_fv3_enspread
> +     module procedure write_fv3_enspread_
> +  end interface
> +
> +contains
> +
> +  subroutine write_fv3_enspread_ (grdin,filename,en_spread,ibin)
>
> While compiling in debug mode, ibin was identified as unused. Please
> remove unused variable.
> ------------------------------
>
> In src/gsi/write_fv3_spread.f90
> <https://github.com/NOAA-EMC/GSI/pull/196#discussion_r [...]

2021-08-16 13:58 UTC, MichaelLueken-NOAA approved these changes

2021-08-16 14:01 UTC, MichaelLueken-NOAA commented
@TingLei-NOAA Thanks for making the changes.  I will now submit this work to the review committee.

2021-08-16 14:03 UTC, TingLei-NOAA commented
Mike,
Thanks a lot!
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624


On Mon, Aug 16, 2021 at 10:01 AM MichaelLueken-NOAA <
***@***.***> wrote:

> @TingLei-NOAA <https://github.com/TingLei-NOAA> Thanks for making the
> changes. I will now submit this work to the review committee.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GSI/pull/196#issuecomment-899535274>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APEFS7FVKRDZAHDYXQA67JLT5EK3JANCNFSM5B4TS7LA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-23 16:55 UTC, MichaelLueken-NOAA commented
The due date for the review committee has past with no feedback.  I will now give final approval to these changes and merge them to the authoritative repository.

2021-08-23 16:55 UTC, merged