Add OMPS NM N20 processing
NOAA-EMC/GSI pull request #202
Opened 2021-08-20 13:31 UTC by LouisKouvaris-NOAA

[global_ozinfo.txt](https://github.com/NOAA-EMC/GSI/files/7021782/global_ozinfo.txt)

Added new OMPS NM QC
Added the top five layers in OMPS NP
Added monitoring OMPS NP N20

2021-08-25 01:40 UTC, HaixiaLiu-NOAA requested changes
I think the changes to the global_ozinfo.txt, the scripts and the setupoz.f90 look good except for the file exgdas_enkf_update.sh which should include ompsnp_n20.

2021-08-25 01:40 UTC, HaixiaLiu-NOAA commented on scripts/exgdas_enkf_update.sh
> +   sattypes_oz(11) = 'ompstc8_n20',
should the ompsnp_n20 be added in this script as well?

2021-08-25 11:54 UTC, MichaelLueken-NOAA commented
@LouisKouvaris-NOAA Should these changes go into the authoritative master, or to the new release/gfsda.v16.x release branch in the authoritative repo?

2021-08-25 13:19 UTC, MichaelLueken-NOAA commented
@LouisKouvaris-NOAA This PR is currently pointing to the authoritative repo's master, not release/gfsda.v16.x.  I should be able to redirect the PR to point from master to release/gfsda.v16.x in the authoritative repo.  Please let me know if I should do this.

2021-09-14 14:59 UTC, LouisKouvaris-NOAA commented
These changes need to go into release/gfsda.v16.x, not the master. Can you also change global_ozinfo.txt to monitor OMPS LP? Thanks.

2021-09-15 10:22 UTC, MichaelLueken-NOAA commented
@LouisKouvaris-NOAA I have changed the branch that these changes will be merged to from the authoritative master to release/gfsda.v16.x.  However, there are now far too many changes and it looks like these changes are from the master itself.  We don't want these in the gfsda.v16.x release branch.  This PR will need to be closed and a new PR will need to be opened where the required changes are made directly to a copy of the release/gfsda.v16.x branch in your fork.

2021-09-15 17:19 UTC, closed without merging

2021-09-15 17:19 UTC, LouisKouvaris-NOAA commented
Resubmitted as PR #212