GSI issue #290.  Port non-operational portions of RadMon to wcoss2.  …
NOAA-EMC/GSI pull request #307
Opened 2022-02-22 18:26 UTC by EdwardSafford-NOAA

Port non-operational portions of RadMon to wcoss2.  Some general cleanup of non-operational portion of package is included as well.  This completes issue #290

2022-02-22 18:27 UTC, EdwardSafford-NOAA commented
@DavidHuber-NOAA if you have a moment can you review this PR?  Thanks!

2022-02-22 22:02 UTC, DavidHuber-NOAA requested changes
Overall, this looks pretty good.  Just a few minor changes.

2022-02-23 14:56 UTC, EdwardSafford-NOAA commented on util/Radiance_Monitor/build_RadMon_cmake.sh
> +elif [[ $target = "s4" ]] ; then
I'll be glad to do that, but please confirm that $MODULESHOME is defined on s4.  I don't have access to that machine.

2022-02-23 14:58 UTC, EdwardSafford-NOAA commented on util/Radiance_Monitor/image_gen/ush/Transfer.sh
> +   if [[ ! -e ${radmon_user_settings} ]]; then
Yes it sure should.

2022-02-23 15:11 UTC, EdwardSafford-NOAA commented on util/Radiance_Monitor/build_RadMon_cmake.sh
> +elif [[ $target = "s4" ]] ; then
Ok, super!  I'll make that change.

2022-02-23 15:31 UTC, EdwardSafford-NOAA commented
@MichaelLueken-NOAA All conversations have been resolved, I've amended the commit, and I think we're good to go now.

2022-02-23 15:47 UTC, DavidHuber-NOAA approved these changes
Looks good!

2022-02-23 15:49 UTC, MichaelLueken-NOAA commented
Since @DavidHuber-NOAA has approved these changes, I will give final approval and merge them to the authoritative repository.

2022-02-23 15:50 UTC, merged