Converge
NOAA-EMC/GSI pull request #443
Opened 2022-07-25 19:28 UTC by jderber-NOAA

Ref: Issue # 375

This change modifies GSI code to use sensible temperature rather than virtual temperature in the rad routines and fixes a minor bug in the radiance and jacobian calculations in setuprad.  These changes do not change results much.

Also, it introduces a new namelist variable optconv.  The optconv variable when set greater than zero (recommended values for global 0.06) down weights channels based on their sensitivity to moisture to improve the convergence characteristics of the minimization.  See issue #375 for details.

2022-07-26 10:07 UTC, MichaelLueken-NOAA commented
Hi @jderber-NOAA, there is an issue that needs to be addressed.  There are 32 commits associated with this PR and it needs to be reduced to a single commit.  To do this:

- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git reset --soft HEAD~1
- git stash
- git remote add upstream https://github.com/NOAA-EMC/GSI.git
- git remote update
- git rebase upstream/develop
- git stash pop
- Please correct the conflicts in src/gsi/crtm_interface.f90 and src/gsi/gsimod.F90 (keep stashed changes)
- git add src/gsi/crtm_interface.f90 src/gsi/gsimod.F90
- `git commit -m "GitHub Issue NOAA-EMC/GSI#375.  Improvements to minimization."`
- git push origin converge --force

This will reduce the number of commits from 32 to 1 and ensure that your PR is up-to-date with the current authoritative develop branch.  Please let me know if you have any questions or encounter any issues.

2022-08-01 13:43 UTC, MichaelLueken-NOAA commented
@ADCollard @emilyhcliu

I know that you are both focused on the GFS v16.3.0 implementation right now, so I wanted to reach out and see if I need to work with John to find someone else to review these changes.  Please let me know as soon as possible.  Thanks!

2022-08-01 19:03 UTC, ADCollard approved these changes
I am sorry this review was delayed.   I think these changes look good and the solution to the minimisation by inflating the the errors based on the size of the humidity Jacobian is a nice idea.  I will test this further in a parallel experiment as I think this could potentially solve some issues we are currently having with the CrIS performance.

2022-08-02 10:23 UTC, MichaelLueken-NOAA requested changes
Hi @jderber-NOAA.  I have completed my visual inspection of the changes.  For the most part, everything looks good.  Please ensure that lines 1788 through 1794 are indented at least two spaces in src/gsi/setuprad.f90.  Also, please replace .ne. with /= on line 1788 in src/gsi/setuprad.f90, as well.  Additionally, while compiling in debug mode, two unused variables were identified.  Please remove unused variables fv and qsat, from lines 1049 and 1115, respectively, in src/gsi/crtm_interface.f90.

Once these changes have been made, please use:

- git add crtm_interface.f90 setuprad.f90
- git commit --amend
- Please save and close the commit message window without changing the commit message.
- git push origin converge --force

Please let me know if you have any questions or encounter any issues.

2022-08-02 10:23 UTC, MichaelLueken commented on src/gsi/crtm_interface.f90
> -     c2(k)=one/(one+fv*q(k))
While compiling in debug mode, fv was identified as being unused.  Please remove fv from line 1049.

2022-08-02 10:23 UTC, MichaelLueken commented on src/gsi/setuprad.f90
> +             end if
Please ensure at least two-space indentation for if statements and do loops.  Please replace .ne. with /= on line 1788.

2022-08-02 10:23 UTC, MichaelLueken commented on src/gsi/crtm_interface.f90
> -     call calc_gfdl_cloudfrac(rho_air,h,q,cloud,hs,garea,qsat,cf_calc)
While compiling in debug mode, qsat was identified as unused.  Please remove qsat from line 1115.

2022-08-03 15:53 UTC, MichaelLueken-NOAA approved these changes
Hi @jderber-NOAA.  Thank you very much for making these changes!  I will submit this work to the review committee once the work that is currently out has been merged.

2022-08-11 15:08 UTC, MichaelLueken-NOAA commented
The due date for feedback from the review committee has past, so I will now give final approval to this update and merge it to the authoritative develop branch.

2022-08-11 15:08 UTC, merged