Github issue #442: Bug fix of reading in radar level2 bufr
NOAA-EMC/GSI pull request #445
Opened 2022-07-27 03:40 UTC by ShunLiu-NOAA

NAM-GSI abort in Aug 2019 and Nov 2021 due to failure of reading in level2 radar bufr with error message:

min,max num_radars= 14 25
index error in radar_bufr_read_all -- program stops -- 0 KPAH
STOP2 ABORTING EXECUTION w/code= 99

The bug was found in building radar master table and finding the radar name index. In a special case, radar PAHG is happen to next to radar KLZK. The master table will be ...KLZKPAHG..., GSI then consider KPAH (radar name) is already available in the master radar table. This is caused GSI abort.

The bug is fixed by using a new function "locindex" to replace "index" to avoid the error of searching radar station name.

2022-07-27 11:04 UTC, MichaelLueken-NOAA commented
@ShunLiu-NOAA Your PR includes five commits rather than a single commit.  To correct this, please use the following commands:

- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git remote add upstream https://github.com/NOAA-EMC/GSI.git
- git remote update
- git rebase upstream/develop
- git checkout readl2_bug_fix
- git checkout master
- git merge --squash readl2_bug_fix
- `git commit -m "GitHub Issue NOAA-EMC/GSI#442. Bug fix of reading in radar level2 bufr."`
- git push origin master --force

Once these steps have been completed, please let me know who you would like for me to assign to your PR as reviewers.

2022-07-27 12:27 UTC, ShunLiu-NOAA commented
Thank you Mike.
I got message below. Is there anything wrong here?


(base) [Shun.Liu@hfe12 gsi] pwd
/scratch2/NCEPDEV/fv3-cam/save/Shun.Liu/gsi/GSI/src/gsi
(base) [Shun.Liu@hfe12 gsi] git merge --squash readl2_bug_fix
Squash commit -- not updating HEAD
Automatic merge went well; stopped before committing as requested
(base) [Shun.Liu@hfe12 gsi] git branch
* master
  readl2_bug_fix

2022-07-27 12:40 UTC, MichaelLueken-NOAA commented
> Thank you Mike. I got message below. Is there anything wrong here?
> 
> (base) [Shun.Liu@hfe12 gsi] pwd /scratch2/NCEPDEV/fv3-cam/save/Shun.Liu/gsi/GSI/src/gsi (base) [Shun.Liu@hfe12 gsi] git merge --squash readl2_bug_fix Squash commit -- not updating HEAD Automatic merge went well; stopped before committing as requested (base) [Shun.Liu@hfe12 gsi] git branch
> 
> * master
>   readl2_bug_fix

@ShunLiu-NOAA 

No, there is nothing wrong.  While using the squash merge, git won't commit the changes.  This is why the following line in the instructions is to use:

`git commit -m "GitHub Issue NOAA-EMC/GSI#442. Bug fix of reading in radar level2 bufr."`

which will commit the modified file with the required commit message.

2022-07-27 13:09 UTC, ShunLiu-NOAA commented
Thanks. Just completed the last step.

2022-07-27 13:22 UTC, MichaelLueken-NOAA commented
> Thanks. Just completed the last step.

@ShunLiu-NOAA Did the final push succeed?  Both the PR and your fork's master branch still have the five commit messages rather than a single commit.  When doing the push, please ensure that you are using:

git push origin master --force

otherwise the push won't happen.

2022-07-27 13:26 UTC, ShunLiu-NOAA commented
Thanks. Mike. Here it is.
(base) [Shun.Liu@hfe12 gsi] git push origin master --force
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 80 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 784 bytes | 196.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/ShunLiu-NOAA/GSI
 + 96c7990a...35ebd6a1 master -> master (forced update)

2022-07-27 13:29 UTC, MichaelLueken-NOAA commented
Thanks, @ShunLiu-NOAA!  The commit is good to go.

2022-07-28 18:34 UTC, TingLei-NOAA approved these changes
Good to me!  Thanks

2022-07-29 15:30 UTC, xyzemc approved these changes

2022-07-29 17:56 UTC, MichaelLueken-NOAA requested changes
Hi @ShunLiu-NOAA, I have completed my review of your bug fix.  Overall, everything looks good.  However, I noted a few issues with the new locindex function.  Please add `implicit none` to the function.  Please give the intent (i.e., intent(in)) for passed variables.  Please ensure that integer declarations include length (i.e., integer(i_kind)).  Please ensure that lines 1066 and 1067 are indented at least two spaces.

Once these modifications are made, please use:

git add read_l2bufr_mod.f90
git commit --amend
git push origin master --force

to commit and push the updated function to your branch.  After this is completed, I should be able to submit this work to the review committee.

Please let me know if you encounter any issues.

2022-07-29 17:56 UTC, MichaelLueken commented on src/gsi/read_l2bufr_mod.f90
> +  integer:: i,locindex,nstr
All integer declarations require a length (i.e., integer(i_kind):: i,locindex,nstr)

2022-07-29 17:56 UTC, MichaelLueken commented on src/gsi/read_l2bufr_mod.f90
> +FUNCTION locindex(stnall,nstr,stn)
All subroutines and functions require implicit none

2022-07-29 17:56 UTC, MichaelLueken commented on src/gsi/read_l2bufr_mod.f90
> +     end if
Please ensure at least two-space indentation for if statements.

2022-07-29 17:56 UTC, MichaelLueken commented on src/gsi/read_l2bufr_mod.f90
> +  integer:: i,locindex,nstr
Please ensure to include intent of passed variables:

integer(i_kind), intent(in):: nstr
character(4),intent(in)::stnall(nstr)
character(4),intent(in)::stn

integer(i_kind):: i,locindex

2022-08-01 09:38 UTC, MichaelLueken-NOAA approved these changes
Thanks, @ShunLiu-NOAA, for addressing my concerns!  Everything looks good.

2022-08-01 11:47 UTC, ShunLiu-NOAA commented
Mike,

Thank you for reviewing this.

Shun

On Fri, Jul 29, 2022 at 1:57 PM MichaelLueken-NOAA ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ShunLiu-NOAA <https://github.com/ShunLiu-NOAA>, I have completed my
> review of your bug fix. Overall, everything looks good. However, I noted a
> few issues with the new locindex function. Please add implicit none to
> the function. Please give the intent (i.e., intent(in)) for passed
> variables. Please ensure that integer declarations include length (i.e.,
> integer(i_kind)). Please ensure that lines 1066 and 1067 are indented at
> least two spaces.
>
> Once these modifications are made, please use:
>
> git add read_l2bufr_mod.f90
> git commit --amend
> git push origin master --force
>
> to commit and push the updated function to your branch. After this is
> completed, I should be able to submit this work to the review committee.
>
> Please let me know if you encounter any issues.
> ------------------------------
>
> In src/gsi/read_l2bufr_mod.f90
> <https://github.com/NOAA-EMC/GSI/pull/445#discussion_r932377464>:
>
> > @@ -1054,4 +1056,16 @@ SUBROUTINE invtllv(ALM,APH,TLMO,CTPH0,STPH0,TLM,TPH)
>    TPH=ASIN(CTPH0*SPH+STPH0*CC)
>    return
>  END SUBROUTINE invtllv
> +FUNCTION locindex(stnall,nstr,stn)
> +  character(4)::stnall(nstr)
> +  character(4)::stn
> +  integer:: i,locindex,nstr
>
> All integer declarations require a length (i.e., integer(i_kind)::
> i,locindex,nstr)
> ------------------------------
>
> In src/gsi/read_l2bufr_mod.f90
> <https://github.com/NOAA-EMC/GSI/pull/445#discussion_r932377857>:
>
> > @@ -1054,4 +1056,16 @@ SUBROUTINE invtllv(ALM,APH,TLMO,CTPH0,STPH0,TLM,TPH)
>    TPH=ASIN(CTPH0*SPH+STPH0*CC)
>    return
>  END SUBROUTINE invtllv
> +FUNCTION locindex(stnall,nstr,stn)
>
> All subroutines and functions require implicit none
> ------------------------------
>
> In src/gsi/read_l2bufr_mod.f90
> <https://github.com/NOAA-EMC/GSI/pull/445#discussion_r932378468>:
>
> > +     if(locindex>0) then
> +      locindex=i
> +      exit
> +     end if
>
> Please ensure at least two-space indentation for if statements.
> ------------------------------
>
> In src/gsi/read_l2bufr_mod.f90
> <https://github.com/NOAA-EMC/GSI/pull/445#discussion_r933202747>:
>
> > +  character(4)::stnall(nstr)
> +  character(4)::stn
> +  integer:: i,locindex,nstr
>
> Please ensure to include intent of passed variables:
>
> integer(i_kind), intent(in):: nstr
> character(4),intent(in)::stnall(nstr)
> character(4),intent(in)::stn
>
> integer(i_kind):: i,locindex
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GSI/pull/445#pullrequestreview-1054319617>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACD5GZ4XDSOK2NEJWKNT3DDVWQLPNANCNFSM54YB2Q7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-04 15:37 UTC, MichaelLueken-NOAA commented
The due date for feedback from the review committee has past, so I will now give final approval to these changes and merge them to the authoritative develop branch.

2022-08-04 15:37 UTC, merged